language: python
python: 3.7
dist: xenial
sudo: true

services: postgresql

env:
  - DJANGO=2.0.7

before_install:
  - export DJANGO_SETTINGS_MODULE=Felize.settings
  - export PYTHONPATH=$HOME/builds/ArCheun/Felize
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE felize;" -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate