# Generated by Django 2.0.7 on 2018-07-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_manager',
        ),
        migrations.AlterField(
            model_name='project',
            name='resources',
            field=models.ManyToManyField(related_name='project_resource', through='projectmanager.ProjectResource', to='projectmanager.Employee'),
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_managers',
            field=models.ManyToManyField(related_name='project_manager', through='projectmanager.ProjectManager', to='projectmanager.Employee'),
        ),
    ]
