# Generated by Django 2.0.7 on 2018-07-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_auto_20180713_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='projectresource',
            name='resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.ProjectResourceType'),
        ),
    ]
