# Generated by Django 2.0.7 on 2018-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0004_auto_20180721_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='allocation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='allocation_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='work_hours_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
