# Generated by Django 2.0.7 on 2018-08-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0006_auto_20180721_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='workentry',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
