# Generated by Django 2.0.7 on 2018-08-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0008_auto_20180804_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CLS', 'Closed')], default='ACT', max_length=3),
        ),
    ]
