# Generated by Django 2.0.7 on 2018-08-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0009_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(max_length=2048)),
                ('url', models.CharField(blank=True, max_length=2048)),
                ('file_path', models.CharField(blank=True, max_length=2048)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneOwnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('INP', 'In-Progress'), ('CMP', 'Completed')], default='PND', max_length=3)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.Employee')),
                ('owner_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneOwnerType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CMP', 'Completed')], default='ACT', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='approved_work_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='projectsprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ProjectSprint'),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneType'),
        ),
        migrations.AddField(
            model_name='milestoneattachment',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ProjectMilestone'),
        ),
    ]
