# Generated by Django 2.0.7 on 2018-08-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0012_auto_20180810_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved_work_days',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=4, null=True),
        ),
    ]
