# Generated by Django 2.0.7 on 2018-08-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0013_auto_20180810_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approved_work_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
