# Generated by Django 2.0.7 on 2018-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0014_auto_20180811_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectresource',
            name='work_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
