# Generated by Django 2.0.7 on 2018-08-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0015_auto_20180811_0005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMilestone',
            new_name='SprintMilestone',
        ),
    ]
