# Generated by Django 2.0.7 on 2018-08-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0016_auto_20180811_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprintmilestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.Employee'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneOwnerType'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneType'),
        ),
    ]
