# Generated by Django 2.0.7 on 2018-08-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0019_auto_20180812_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',), 'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('employee_id',), 'verbose_name': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='milestoneattachment',
            options={'verbose_name': 'Milestone Attachment'},
        ),
        migrations.AlterModelOptions(
            name='milestoneownertype',
            options={'verbose_name': 'Milestone Owner Type'},
        ),
        migrations.AlterModelOptions(
            name='milestonetype',
            options={'verbose_name': 'Milestone Type'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'verbose_name': 'Organization'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('name',), 'verbose_name': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='projectmanager',
            options={'verbose_name': 'Project Manager'},
        ),
        migrations.AlterModelOptions(
            name='projectresource',
            options={'verbose_name': 'Resource'},
        ),
        migrations.AlterModelOptions(
            name='projectresourcetype',
            options={'ordering': ('name',), 'verbose_name': 'Resource Type'},
        ),
        migrations.AlterModelOptions(
            name='projectsprint',
            options={'verbose_name': 'Sprint'},
        ),
        migrations.AlterModelOptions(
            name='sprintmilestone',
            options={'verbose_name': 'Milestone'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ('name',), 'verbose_name': 'Task Status'},
        ),
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name': 'User Story'},
        ),
        migrations.AlterModelOptions(
            name='workentry',
            options={'ordering': ('worked_date',), 'verbose_name': 'Work Entry'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(max_length=2048, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.CharField(blank=True, max_length=2048, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.CharField(blank=True, max_length=2048, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='milestoneattachment',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Attachment', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='milestoneattachment',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.SprintMilestone', verbose_name='Milestone'),
        ),
        migrations.AlterField(
            model_name='milestoneownertype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='milestonetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_work_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='No. of Approved Days'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CLS', 'Closed')], default='ACT', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='allocation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Allocation Start Date'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='allocation_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Allocation Start Date'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.ProjectResourceType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='projectresource',
            name='work_hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Work Hrs./Day'),
        ),
        migrations.AlterField(
            model_name='projectresourcetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='projectsprint',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CMP', 'Completed')], default='ACT', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.Employee', verbose_name='Assigned Employee'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='comment',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='due_date',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='owner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneOwnerType', verbose_name='Owner Type'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ProjectSprint', verbose_name='Sprint'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('INP', 'In-Progress'), ('CMP', 'Completed')], default='PND', max_length=3, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sprintmilestone',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanager.MilestoneType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.IntegerField(verbose_name='Estimated Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanager.ProjectResource', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.TaskStatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.UserStory', verbose_name='User Story'),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='worked_date',
            field=models.DateField(verbose_name='Worked Date'),
        ),
    ]
