# Generated by Django 2.0.7 on 2018-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0020_auto_20180814_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
