# Generated by Django 2.0.7 on 2018-08-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0024_auto_20180825_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Estimated Time'),
        ),
    ]
