from .organization_views import organization_list, organization_details
from .base_views import dashboard
from .project_views import ProjectUpdateView, ProjectListView, ProjectCreateView
from .project_resource_views import ProjectResourceListView, ProjectResourceCreateView, ProjectResourceUpdateView
from .work_entries_views import WorkEntryCreateView, WorkEntryUpdateView, WorkEntryListView
